sudo: required
services:
  - docker

before_install:
  - docker build -t jond02/docker-react -f Dockerfile.dev .

script:
  - docker run jond02/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-udemy"
  env: "DockerReactUdemy-env"
  bucket_name: "elasticbeanstalk-us-west-2-736338261372"
  bucket_path: "docker-react-udemy"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"